### ISSUE TITLE
Roadmap to 0.1.0

### ISSUE THREAD

**Issue by dpytaylo** [dpytaylo/simple-messenger#1]
In the first roadmap I would like to implement these features:

#### Account Creation and Login:
- [ ] Users can create accounts and log in using email or Google OAuth2 authentication (#2)
- [ ] User authentication through email and Google OAuth2
#### Profile Visibility:
- [ ] All users can view the profiles of other users within the application
#### Profile Management:
- [ ] Users have the ability to edit their profiles, updating personal information
- [ ] Users can delete their accounts
#### Channel Creation:
- [ ] Users can open or create new channels within the application
#### Messaging:
- [ ] Users can send messages to channels
- [ ] Users receive notifications for messages in channels they are part of
